version: '3.8'

services:
  nest-backend:
    build: ./server
    ports:
      - "3004:3004"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    restart: always
